### ISSUE TITLE
Error during Install-MRP-app.sh

### ISSUE THREAD

**Issue by gitwilbug1** [Microsoft/PartsUnlimitedMRP#74]
/var/tmp# Exception in thread "main" java.lang.UnsupportedClassVersionError: smpl/ordering/OrderingConfiguration : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:161)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at java.lang.Thread.run(Thread.java:745)

**Comment by julienstroheker** [comment]
@gitwilbug1 can you give me more context about this error ?
What are you trying to do ?
Thanks

**Comment by julienstroheker** [comment]
@gitwilbug1 should be fixed now using the new Hands on Labs

**Comment by gitwilbug1** [comment]
Sorry for late reply.  I got it resolved as well by adding a apt repository.  Then the correct jdk was installed.
# Install packages
add-apt-repository ppa:openjdk-r/ppa -y
apt-get update
apt-get install openjdk-8-jdk -y
apt-get install openjdk-8-jre -y
apt-get install mongodb -y
apt-get install tomcat7 -y
apt-get install wget -y
